# Role to move edovo.com DNS Zones to /etc/bind/zones and restart BIND9
---
# Install Packages
  - name: Install BIND9
    apt:
      name: bind9
      state: installed
      update_cache: true
    register: task_result
    until: task_result is success
    retries: 5
    delay: 2

  - name: Install BIND9 Utilities
    apt:
      name: bind9utils
      state: installed
      update_cache: true
    register: task_result
    until: task_result is success
    retries: 5
    delay: 2

# Create logging directory if it doesn't exist
  - name: Create Logging Directory
    file:
      path: /var/log/named
      state: directory
      owner: bind
      group: bind
      mode: 0755

# Create logging files
  - name: Create DNS Logging Files
    file:
      path: "{{ item }}"
      state: touch
      mode: 0775
    with_items:
    - /var/log/named/default.log
    - /var/log/named/general.log
    - /var/log/named/database.log
    - /var/log/named/security.log
    - /var/log/named/config.log
    - /var/log/named/resolver.log
    - /var/log/named/xfer-in.log
    - /var/log/named/xfer-out.log
    - /var/log/named/notify.log
    - /var/log/named/client.log
    - /var/log/named/unmatched.log
    - /var/log/named/queries.log
    - /var/log/named/network.log
    - /var/log/named/update.log
    - /var/log/named/dispatch.log
    - /var/log/named/dnssec.log
    - /var/log/named/lame-servers.log

# Create Zones directory if it doesn't exist
  - name: Create Zones Directory
    file:
      path: /etc/bind/zones
      state: directory
      owner: root
      group: root
      mode: 0755

# Copy named.conf.options
  - name: Copy named.conf.options
    copy:
      src: named.conf.options
      dest: /etc/bind/named.conf.options
      owner: root
      group: root
      mode: 0755

# Copy named.conf.local
  - name: Copy named.conf.local
    copy:
      src: named.conf.local
      dest: /etc/bind/named.conf.local
      owner: root
      group: root
      mode: 0755

# Copy db.192.168
  - name: Copy db.192.168
    copy:
      src: db.192.168
      dest: /etc/bind/zones/db.192.168
      owner: root
      group: root
      mode: 0755

# Copy db.mcornstu.net
  - name: Copy db.mcornstu.net
    copy:
      src: db.mcornstu.net
      dest: /etc/bind/zones/db.mcornstu.net
      owner: root
      group: root
      mode: 0755

# Restart BIND
  - name: Restart BIND9
    service:
      name: bind9
      state: restarted
